from tkinter import *
r=Tk()
lbl1=Label(r,text="First Name :")
e1=Entry(r,justify=CENTER)
lbl2=Label(r,text="Middle Name :")
e2=Entry(r,justify=RIGHT)
lbl3=Label(r,text="Last Name :")
e3=Entry(r)
e1.pack()
e2.pack()
e3.pack()
r.mainloop()