from tkinter import *
r=Tk()
r.configure(background="orange")
label1=Label(r,text="Allen",font="Time 19 bold")
label2=Label(r,text="stephi",font="arial 14 bold italic")
label3=Label(r,text="john",wraplength=1)
label4=Label(r,text="miller",state=DISABLED)
label5=Label(r,text="Allen",state=ACTIVE)
label1.pack()
label2.pack()
label3.pack()
label4.pack()
label5.pack()
r.mainloop()